yourssu/ssufid

- .github/CODEOWNERS
- .github/workflows/lint.yml
X
- 코드 린팅을 위한 `rustfmt`, `clippy` 를 실행하는 lint workflow 작성
- 리뷰어 등록을 위한 CODEOWNERS 파일 작성
>
> [ci] 코드 린팅을 위한 lint workflow

- .gitignore
X
`.ssufid`, `out` 디렉토리를 `.gitignore`에 추가합니다.
>
> [chore] `ssufid` 디렉토리를 gitignore에 추가

- src/core/rss.rs
Resolved #19
[atom](http://www.w3.org/2005/Atom) Extension을 이용해 `atom:updated` 필드를 만들고, 업데이트 일시를 표현합니다.
>
> [feat] `atom` extension의 `updated` 필드를 이용한 업데이트 일시 표현

- Cargo.lock
- Cargo.toml
- src/main.rs
Resolves #24 
- `out/{plugin}/rss.xml` 에 rss 파일을 저장합니다.
- `futures::future::join_all`로 병렬 처리를 수행합니다.
- `color_eyre`를 통해 메시지에 색상을 추가합니다.
>
> [feat] rss 쓰기 구현

- .github/workflows/test.yml
resolves #28
- test.yml 추가
- codecov 세팅 ([rusaint의 build-test.yml](https://github.com/EATSTEAK/rusaint/blob/main/.github/workflows/build-test.yml) 참고 했습니다)
- 링크: https://app.codecov.io/gh/yourssu/ssufid
>
- [공식 예시](https://github.com/codecov/example-rust/blob/main/.github/workflows/rust.yml)에서는 actions-rs/grcov로 커버리지 생성한 것 같은데 이건 옛날 방식이라서 안 쓰는 건가요? (actions-rs가 아카이브 되긴 했더라구요)
- `cargo build`는 굳이 실행하지 않아도 괜찮을까요?
> [ci] 테스트 워크플로 및 커버리지 설정

- Cargo.lock
- src/core/mod.rs
X
기존 파일과 새로운 파일의 차이점이 없을 때, `updated_at` 필드를 기존 파일에서 가져오도록 수정
>
> [fix] 기존 파일의 `updated_at` 필드를 보존하도록 수정

- .gitignore
- src/core/mod.rs
X
- .gitignore에 `.cache` 경로 추가
- save_cache에서 unwrap 호출 부분 `?` 연산자로 변경
> [chore] 일부 놓친 코드 수정

- src/core/rss.rs
Resolved #60 
atom namespace를 추가하여 rss 파일이 브라우저에서 제대로 표시되지 않는 문제를 수정했습니다.
>
> [fix] `atom` namespace를 추가하여 rss 오류 수정

- src/plugins/ssu_catch.rs
- resolved #52 
- Iterator의 메서드를 활용하여 크롤링 과정을 함수형 프로그래밍으로 리팩토링 하였습니다.
Rust Iterator 진짜 좋네요 👍
> [refactor] Iterator의 메서드를 활용하여 크롤링 과정을 함수형으로 리팩토링

- src/core/mod.rs
- src/plugins/ssu_catch.rs
X
- SsufidPlugin에 BASE_URL 연관 상수 추가
- SsufidSiteData의 `source` 필드를 BASE_URL로 넣어주기
>
> [feat] SsufidPlugin에 BASE_URL 연관 상수 추가

- src/core/rss.rs
Resolved #64
- RSS 스펙에 맞게 수정했습니다.
- `description` 추가(content의 50자까지 truncate)
- `atom:updated`를 `Rfc3339`를 사용하도록 변경
>
> fix: rss validation check

- src/core/rss.rs
> [refactor] description truncate 방법 변경

- src/main.rs
X
`Future`의 타입 호환 문제로 여러 플러그인을 지원하지 못하는 문제를 수정했습니다.
이제 SsufidPluginRegistry에 enum variant를 추가하는 형식으로 플러그인을 등록하고, construct_tasks에서는 해당 enum을 통해 future를 생성합니다.
>
> [fix] 여러 플러그인을 지원하도록 `SsufidPluginRegistry` 생성

- Cargo.lock
- Cargo.toml
- src/core/rss.rs
- src/main.rs
- src/plugins/mod.rs
- src/plugins/ssu_path/mod.rs
- src/plugins/ssu_path/model.rs
- src/plugins/ssu_path/model/table.rs
- src/plugins/ssu_path/sso.rs
- src/plugins/ssu_path/utils.rs
Resolved #61
SSU-PATH 플러그인 구현
TODO
>
> [feat] SSU-PATH 플러그인

- src/core/mod.rs
- src/main.rs
- src/plugins/media.rs
- src/plugins/mod.rs
- src/plugins/ssu_path/mod.rs
Resolved #88
- `Attachment::from_guess` 메소드 추가(`name`으로부터 Mime을 guess)
- 글로벌미디어학부 공지사항 크롤링 구현
>
> feat: 글로벌미디어학부 플러그인

- .github/actions/analyze-report/action.yml
X
multiline json이 script에 포함되어 액션 리포트에 실패하는 문제를 수정합나다.
>
> [ci] jq compact 출력 사용

- .github/actions/analyze-report/action.yml
> [fix] 슬랙 실패 메시지가 전송되지 않는 현상 수정

- .github/actions/analyze-report/action.yml
> [fix] 잘못된 슬랙 메시지 형식 수정

- .github/workflows/daemon.yml
X
- daemon ci 에서 접근할 수 없는 context에 접근하는 체크를 삭제합니다.
>
> [fix] 접근할 수 없는 체크 삭제

- .github/workflows/daemon.yml
- .github/workflows/dry-run.yml
> [fix] dry-run이 커밋을 시도하지 않도록 수정

- .github/workflows/daemon.yml
- .github/workflows/dry-run.yml
X
- 기본 가져오는 포스트 수를 30, dry-run 시 20으로 수정했습니다.
- dry-run에서 커밋을 시도하지 않도록 수정했습니다.
>
> [ci] 가져오는 기본 포스트 수 및 dry-run 포스트 수 제한

- .github/workflows/daemon.yml
X
의도치 않게 dry-run 에서 작업이 실행되는 문제 수정
>
> ci: fix composite conditions

- Cargo.lock
- Cargo.toml
- packages/cli/Cargo.toml
- packages/cli/src/main.rs
- plugins/chemeng/Cargo.toml
- plugins/chemeng/src/lib.rs
Resolved #180 
>
```
…in and rename the package.
Specifically, I moved the plugin to the `plugins/chemeng` directory and renamed the package from `ssufid_chemeng` to `chemeng`.
This change involved:
- Renaming the plugin directory.
- Updating the package name in `plugins/chemeng/Cargo.toml`.
- Updating the workspace dependency in the root `Cargo.toml`.
- Updating the dependency and import statements in the CLI package (`packages/cli`).
All build, lint, format, and test checks pass after these changes. This helps align the plugin's location and name for better consistency.
```
> [feat] chemeng.ssu.ac.kr

- Cargo.lock
- Cargo.toml
- packages/cli/Cargo.toml
- packages/cli/src/main.rs
- plugins/study/Cargo.toml
- plugins/study/src/lib.rs
- plugins/study/src/model.rs
> [feat] study.ssu.ac.kr

- Cargo.lock
- Cargo.toml
- packages/cli/Cargo.toml
- packages/cli/src/main.rs
- plugins/ssfilm/Cargo.toml
- plugins/ssfilm/src/lib.rs
> [feat] ssfilm.ssu.ac.kr

- plugins/lawyer/src/lib.rs
- plugins/materials/src/lib.rs
- plugins/ssudorm/src/lib.rs
Resolved #209 
- `materials`, `ssudorm`, `lawyer` 플러그인의 테스트 실패 해결
>
> [fix] multiple test failures

- plugins/chemeng/src/lib.rs
- plugins/common/src/common/gnuboard/mod.rs
- plugins/ee/src/lib.rs
- plugins/infocom/src/lib.rs
- plugins/inso/src/lib.rs
- plugins/lawyer/src/lib.rs
- plugins/lifelongedu/src/lib.rs
- plugins/materials/src/lib.rs
- plugins/me/src/lib.rs
- plugins/mediamba/src/lib.rs
- plugins/oasis/src/lib.rs
- plugins/ssfilm/src/lib.rs
- plugins/ssudorm/src/lib.rs
- plugins/startup/src/lib.rs
X
1.88.0 버전의 clippy lint를 적용합니다.
>
> [lint] clippy 적용

- Cargo.lock
- Cargo.toml
- packages/cli/Cargo.toml
- packages/cli/src/main.rs
- plugins/biz/Cargo.toml
- plugins/biz/src/lib.rs
Resolved #172
>
```
- I renamed the plugin directory from `plugins/ssufid_biz` to `plugins/biz`.
- I updated all relevant paths in `Cargo.toml` files to reflect the new directory structure. The crate name `ssufid_biz` is preserved.
- I removed the temporary `temp_fetcher` directory.
These changes address your feedback to clean up the project structure. All builds, lints, and tests pass.
```
> [feat] biz.ssu.ac.kr

- .github/workflows/daemon.yml
- .github/workflows/dry-run.yml
X
daemon 워크플로에서 제외할 사이트를 지정할 수 있도록 인풋을 추가합니다.
>
> [ci] add excludes input to daemon workflow
